config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  concern :check do
    post :check, on: :collection, defaults: { format: :json }
  end

  concern :toggle do
    post :toggle, on: :member, defaults: { format: :json }
  end

  concern :priority do
    post :priority, on: :member, defaults: { format: :json }
  end

  concern :search do
    get :search, on: :collection
  end

  concern :stories do
    post 'stories/:slug' => :story, on: :collection, as: :story
  end

  get 'comunit/:table_name/:uuid' => 'network#show', as: nil
  put 'comunit/:table_name/:uuid' => 'network#pull', as: nil

  scope :posts, controller: :posts do
    get '/' => :index, as: :posts
    get ':id-:slug' => :show, as: :post, constraints: { id: /\d+/ }
  end
  resources :authors, only: %i[index show]

  namespace :admin do
    # Comunit component
    resources :sites, concerns: %i[check search toggle]

    # Posts component
    resources :posts, concerns: %i[check search toggle]
    resources :post_groups, concerns: %i[check toggle]
    resources :authors, concerns: %i[check toggle]

    # Taxonomy component
    resources :taxa, concerns: %i[check search toggle]
  end

  namespace :my do
    resources :posts, concerns: %i[check toggle]
  end
end

app/models/post.rb
# frozen_string_literal: true

# Post
#
# Attributes:
#   agent_id [Agent], optional
#   body [text]
#   created_at [DateTime]
#   data [jsonb]
#   ip_address_id [IpAddress], optional
#   featured [boolean]
#   lead [text], optional
#   paywall [Boolean]
#   publication_time [datetime]
#   rating [float]
#   simple_image_id [SimpleImage], optional
#   slug [string]
#   source_link [string], optional
#   source_name [string], optional
#   title [string]
#   updated_at [DateTime]
#   user_id [User]
#   uuid [uuid]
#   video [boolean]
#   view_count [integer]
#   visible [boolean]
class Post < ApplicationRecord
  include BelongsToSite
  include Checkable
  include HasOwner
  include HasSimpleImage
  include HasTrack
  include HasUuid
  include MetaTexts
  include Toggleable

  LEAD_LIMIT = 5000
  META_LIMIT = 255
  TITLE_LIMIT = 255
  URL_PATTERN = %r{https?://([^/]+)/?.*}

  toggleable :visible, :featured, :paywall
  paginates_per 12

  belongs_to :user, optional: true
  has_many :post_attachments, dependent: :destroy
  has_many :post_images, dependent: :destroy
  has_many :post_links, dependent: :destroy
  has_many :post_notes, dependent: :destroy
  has_many :post_references, dependent: :destroy

  after_initialize { self.publication_time = Time.now if publication_time.nil? }
  before_validation :prepare_slug
  before_validation :prepare_source_names

  validates_presence_of :title, :body
  validates_length_of :title, maximum: TITLE_LIMIT
  validates_length_of :lead, maximum: LEAD_LIMIT
  validates_length_of :source_link, maximum: META_LIMIT
  validates_length_of :source_name, maximum: META_LIMIT

  scope :featured, -> { where(featured: true) }
  scope :visible, -> { where(visible: true) }
  scope :recent, -> { order('publication_time desc') }
  scope :popular, -> { order('rating desc') }
  scope :published, -> { where('publication_time <= current_timestamp') }
  scope :search, ->(v) { where("posts_tsvector(title, lead, body) @@ phraseto_tsquery('russian', ?)", v) }
  scope :list_for_visitors, -> { visible.published.includes(:simple_image, :user).recent }
  scope :list_for_administration, -> { includes(:simple_image, :user).order('id desc') }
  scope :list_for_owner, ->(v) { includes(:simple_image, :user).owned_by(v).recent }
  scope :archive, -> { f = Arel.sql('date(publication_time)'); distinct.order(f).pluck(f) }
  scope :posted_after, ->(v) { where('publication_time >= ?', v) }
  scope :pubdate, ->(v) { where('date(publication_time) = ?', v) }
  scope :f_visible, ->(f) { where(visible: f.to_i.positive?) unless f.blank? }
  scope :filtered, ->(f) { f_visible(f[:visible]) }

  # @param [Integer] page
  # @param [Hash] filter
  def self.page_for_administration(page = 1, filter = {})
    filtered(filter).list_for_administration.page(page)
  end

  # @param [Integer] page
  # @param [Integer] per_page
  def self.page_for_visitors(page = 1)
    list_for_visitors.page(page)
  end

  # @param [User] user
  # @param [Integer] page
  def self.page_for_owner(user, page = 1)
    list_for_owner(user).page(page)
  end

  def self.entity_parameters
    %i[
      body lead publication_time rating simple_image_id source_name source_link
      title video
    ] + toggleable_attributes
  end

  def self.creation_parameters
    entity_parameters
  end

  def world_url
    "/posts/#{id}-#{slug}"
  end

  def text_for_link
    title
  end

  private

  def prepare_slug
    postfix = (created_at || Time.now).strftime('%d%m%Y')

    self.slug = "#{Canonizer.transliterate(title.to_s)}_#{postfix}"

    slug_limit = 200 + postfix.length + 1
    self.slug = slug.downcase[0..slug_limit]
  end

  def prepare_source_names
    return unless source_name.blank? && !source_link.blank?

    self.source_name = URI.parse(source_link).host
  rescue URI::InvalidURIError
    self.source_name = URL_PATTERN.match(source_link)[1]
  end
end

app/controllers/admin/posts_controller.rb
# frozen_string_literal: true

# Handling posts
class Admin::PostsController < AdminController
  include CrudEntities
  include ToggleableEntity

  before_action :set_entity, except: %i[check create index new]

  private

  def component_class
    Biovision::Components::PostsComponent
  end
end

app/controllers/my/posts_controller.rb
# frozen_string_literal: true

# User-side post handling
class My::PostsController < ProfileController
  include CrudEntities
  include ToggleableEntity

  before_action :set_entity, except: %i[check create index new]

  private

  def path_after_save
    @entity.world_url
  end

  def component_class
    Biovision::Components::PostsComponent
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# Public part of posts component
class PostsController < ApplicationController
  # get /posts
  def index
    @collection = Post.page_for_visitors(current_page)
  end

  # get /posts/:id-:slug
  def show
    @entity = Post.list_for_visitors.find_by(id: params[:id])
    handle_http_404 if @entity.nil?
  end
end

app/views/my/posts/_form.html.erb
<%= form_with(**Biovision::Components::BaseComponent.form_options(entity, :my)) do |f| %>
  <%= render partial: 'shared/list_of_errors', locals: { entity: entity } %>

  <dl class="fields">
    <%= render partial: 'components/comunit/forms/image', locals: { f: f} %>
    <%= render partial: 'shared/forms/text_field', locals: { f: f, field: :title } %>
    <%= render partial: 'shared/forms/text_area', locals: { f: f, field: :lead, options: {rows: 3} } %>
    <%=
      render(
        partial: 'shared/forms/text_area',
        locals: {
          f: f,
          field: :body,
          data: {
              wysiwyg: true,
              upload_url: '/'
          }
        }
      )
    %>
    <%= render partial: 'shared/forms/fields', locals: { f: f, fields: %w[publication_time source_name source_link] } %>
    <%= render partial: 'shared/forms/entity_flags', locals: { f: f } %>
    <%= render partial: 'shared/forms/meta_texts', locals: { f: f } %>
  </dl>

  <%= render 'shared/forms/state_container' %>

  <div class="buttons">
    <%= hidden_field_tag :entity_id, entity.id %>
    <%= f.button t(:save), class: 'button button-save' %>
  </div>
<% end %>

<%= render 'components/comunit/wysiwyg' %>

app/views/my/posts/index.html.erb
<% content_for :meta_title, t('.title', page: current_page) %>
<% content_for :breadcrumbs do %>
  <%= my_home_link %>
  <span><%= t('my.posts.nav_item.text') %></span>
<% end %>

<article>
  <div class="content-wrapper">
    <h1><%= t('.heading') %></h1>

    <nav class="entity-actions">
      <%= create_icon(new_my_post_path) %>
    </nav>

    <%=
      render(
        partial: 'components/posts/widgets/post_list',
        locals: { collection: @collection }
      )
    %>
  </div>
</article>

app/views/my/posts/show.html.erb
<% content_for :meta_title, t('.title', title: @entity.title) %>
<% content_for :breadcrumbs do %>
  <%= link_to(t('my.index.index.nav_text'), my_path) %>
  <%= link_to(t('my.posts.nav_item.text'), my_posts_path) %>
  <span><%= @entity.title %></span>
<% end %>

<article>
  <h1><%= @entity.title %></h1>

  <nav class="entity-actions">
    <%= world_icon(@entity) if @entity.visible? %>
    <%= edit_icon(@entity) %>
  </nav>

  <dl class="fields">
    <%= render partial: 'shared/entity/simple_image', locals: { entity: @entity } %>
    <%= render partial: 'shared/entity/text_field', locals: { entity: @entity, field: :title } %>
    <%= render partial: 'shared/entity/slug', locals: { entity: @entity } %>
    <%= render partial: 'shared/entity/raw_text_field', locals: { entity: @entity, field: :lead } %>
    <%= render partial: 'shared/entity/raw_text_field', locals: { entity: @entity, field: :body } %>
    <%= render partial: 'shared/entity/text_fields', locals: { entity: @entity, fields: %w[publication_time source_name source_link]} %>
    <%= render partial: 'shared/entity/meta_texts', locals: { entity: @entity } %>
    <%= render partial: 'shared/entity/uuid', locals: { entity: @entity } %>
    <%= render partial: 'shared/entity/timestamps', locals: { entity: @entity } %>
  </dl>
</article>