config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  concern :check do
    post :check, on: :collection, defaults: { format: :json }
  end

  concern :toggle do
    post :toggle, on: :member, defaults: { format: :json }
  end

  concern :priority do
    post :priority, on: :member, defaults: { format: :json }
  end

  concern :search do
    get :search, on: :collection
  end

  concern :stories do
    post 'stories/:slug' => :story, on: :collection, as: :story
  end

  get 'comunit/:table_name/:uuid' => 'network#show', as: nil
  put 'comunit/:table_name/:uuid' => 'network#pull', as: nil

  scope :posts, controller: :posts do
    get '/' => :index, as: :posts
    get ':id-:slug' => :show, as: :post, constraints: { id: /\d+/ }
  end
  resources :authors, only: %i[index show]

  namespace :admin do
    # Comunit component
    resources :sites, concerns: %i[check search toggle]

    # Posts component
    resources :posts, concerns: %i[check search toggle]
    resources :post_groups, concerns: %i[check toggle]
    resources :authors, concerns: %i[check toggle]

    # Taxonomy component
    resources :taxa, concerns: %i[check search toggle]
  end

  namespace :my do
    resources :posts, concerns: %i[check toggle]
  end
end

app/models/author.rb
# frozen_string_literal: true

# Post author
# 
# Attributes:
#   about [text]
#   name [string]
#   patronymic [string]
#   simple_image_id [SimpleImage], optional
#   surname [string]
#   title [string]
#   user_id [User], optional
#   visible [boolean]
class Author < ApplicationRecord
  include Checkable
  include HasSimpleImage
  include HasOwner
  include Toggleable

  NAME_LIMIT = 70
  TITLE_LIMIT = 250

  toggleable :visible

  belongs_to :user, optional: true

  validates_presence_of :name, :surname
  validates_length_of :name, maximum: NAME_LIMIT
  validates_length_of :patronymic, maximum: NAME_LIMIT
  validates_length_of :surname, maximum: NAME_LIMIT
  validates_length_of :title, maximum: TITLE_LIMIT

  scope :ordered_by_name, -> { order(:surname, :name, :patronymic)}
  scope :visible, -> { where(visible: true) }
  scope :list_for_visitors, -> { included_image.visible.ordered_by_name }
  scope :list_for_administration, -> { included_image.ordered_by_name }

  def self.entity_parameters
    %i[about name patronymic simple_image_id surname title user_id visible]
  end

  def full_name
    [surname, name, patronymic].reject(&:blank?).join(' ')
  end

  def text_for_link
    full_name
  end

  def world_url
    "/authors/#{id}-#{CGI::escape(full_name)}"
  end
end

app/controllers/admin/authors_controller.rb
# frozen_string_literal: true

# Handling post authors
class Admin::AuthorsController < AdminController
  include CrudEntities
  include ToggleableEntity

  before_action :set_entity, except: %i[check create index new]

  private

  def component_class
    Biovision::Components::PostsComponent
  end
end

app/controllers/authors_controller.rb
# frozen_string_literal: true

# Authors for visitors
class AuthorsController < ApplicationController
  # get /authors
  def index
    @collection = Author.list_for_administration
  end

  # get /authors/:id
  def show
    author_id = params[:id].split('-').first.to_i
    @entity = Author.list_for_visitors.find_by(id: author_id)
    handle_http_404 if @entity.nil?
    @collection = Post.owned_by(@entity&.user).page_for_visitors(current_page)
  end

  private

  def component_class
    Biovision::Components::PostsComponent
  end
end

app/views/admin/authors/_form.html.erb
<%= form_with(**Biovision::Components::BaseComponent.form_options(entity)) do |f| %>
  <%= render partial: 'shared/list_of_errors', locals: { entity: entity } %>

  <dl class="fields">
    <%= entity_form_block(f, :simple_image) %>
    <%=
      render(
        partial: 'shared/forms/fields',
        locals: {
          f: f,
          fields: %w[surname name patronymic title about]
        }
      )
    %>
    <%= entity_form_block(f, :entity_flags) %>
  </dl>

  <%= render 'shared/forms/state_container' %>

  <div class="buttons">
    <%= hidden_field_tag :entity_id, entity.id %>
    <%= f.button t(:save), class: 'button button-save' %>
  </div>
<% end %>

app/views/admin/authors/_nav_item.html.erb
<div>
  <%= link_to t('.text'), admin_authors_path %>
</div>
<div class="description">
  <%= t('.description') %>
</div>

app/views/admin/authors/index.html.erb
<% content_for :meta_title, t('.title') %>
<% content_for :breadcrumbs do %>
  <%= admin_biovision_component_link(component_handler.component) %>
  <span><%= t('admin.authors.nav_item.text') %></span>
<% end %>

<article>
  <h1><%= t('.heading') %></h1>

  <nav class="entity-actions">
    <%= world_icon(authors_path) %>
    <% if component_handler.permit?("#{controller_name}.edit") %>
      <%= create_icon(new_admin_author_path) %>
    <% end %>
  </nav>

  <%= entity_list(@collection) %>
</article>

app/views/admin/authors/show.html.erb
<% content_for :meta_title, t('.title', name: @entity.full_name) %>
<% content_for :breadcrumbs do %>
  <%= admin_biovision_component_link(component_handler.component) %>
  <%= link_to(t('admin.authors.nav_item.text'), admin_authors_path) %>
  <span><%= @entity.full_name %></span>
<% end %>

<article>
  <h1><%= @entity.full_name %></h1>

  <nav class="entity-actions">
    <%= world_icon(@entity) %>
    <%= edit_icon(@entity) %>
    <%= destroy_icon(@entity) %>
  </nav>

  <dl class="fields">
    <%= render partial: 'shared/entity/simple_image', locals: { entity: @entity } %>
    <%= render partial: 'shared/entity/linked_entity', locals: { entity: @entity.user } %>
    <%= render partial: 'shared/entity/text_fields', locals: { entity: @entity, fields: %w[surname name patronymic title] } %>
    <% unless @entity.about.blank? %>
      <div>
        <dt><%= @entity.class.human_attribute_name(:about) %></dt>
        <dd>
          <div class="text">
            <%= simple_format(@entity.about) %>
          </div>
        </dd>
      </div>
    <% end %>
  </dl>

  <%= entity_toggle(@entity) %>
</article>